sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "123456"
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tBBKBnA5MjwCkfJbjig
    access-key-secret: beuQAbjWH39s0CZwKS8Kbqg4JwOoLa
    bucket-name: liang-sky-take-out
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wxe5244a5bcfdc50c7
    secret: 37f6d549e0d1c17ceda7717672b2cf67
    mchid:
    mchSerialNo:
    privateKeyFilePath:
    apiV3Key:
    weChatPayCertFilePath:
    notifyUrl:
    refundNotifyUrl:
